#!/bin/sh

target=('class' 'get-post' 'get-all-posts' 'login' 'relationship' 'show-user')

for t in "${target[@]}"; do
  echo "Building target: $t.txt"
  java -jar ./plantuml.jar src/$t.txt -o ../img
  [ $? -eq 0 ] && echo "Success building $t.txt" || echo "Error while building $t.txt"
done
